name: Framework - Laravel / Symfony Test

on:
  workflow_dispatch:
  pull_request:
    paths:
      - 'src/**'
      - 'docker/**'
      - '.env*'

jobs:
  laravel-test:
    name: ğŸ“Š Test Laravel
    runs-on: ubuntu-latest

    steps:
      - name: ğŸ’¾ Checkout code
        uses: actions/checkout@v4

      - name: ğŸ“‚ Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: ğŸ›  Prepare .env and extract PHP_VERSION
        run: |
          cp .env.example .env
          echo "PHP_VERSION=$(grep PHP_VERSION .env | cut -d '=' -f2)" >> $GITHUB_ENV

      - name: ğŸ’¾ Restore build cache
        uses: actions/cache@v4
        with:
          path: /tmp/.buildx-cache-${{ env.PHP_VERSION }}
          key: ${{ format('{0}-php-{1}-{2}', runner.os, env.PHP_VERSION, hashFiles(format('docker/php/{0}/Dockerfile', env.PHP_VERSION)) ) }}
          restore-keys: |
            ${{ runner.os }}-php-${{ env.PHP_VERSION }}-

      - name: ğŸ’ª Build Docker environment (with cache)
        run: |
          docker buildx create --use
          docker buildx build \
            --tag php-dev:${{ env.PHP_VERSION }} \
            --file docker/php/${{ env.PHP_VERSION }}/Dockerfile \
            --cache-from=type=local,src=/tmp/.buildx-cache-${{ env.PHP_VERSION }} \
            --cache-to=type=local,dest=/tmp/.buildx-cache-new-${{ env.PHP_VERSION }} \
            --load \
            .

      - name: ğŸ’¾ Save updated cache
        if: always()
        run: |
          rm -rf /tmp/.buildx-cache-${{ env.PHP_VERSION }}
          mv /tmp/.buildx-cache-new-${{ env.PHP_VERSION }} /tmp/.buildx-cache-${{ env.PHP_VERSION }}

      - name: ğŸš€ Start Laravel stack
        run: make up-mysql

      - name: ğŸ¤– Create new Laravel App
        run: make composer-create-project project=laravel/laravel name=laravel-test

      - name: ğŸ”§ Run Laravel Artisan about
        run: make run-php-command project=laravel-test command="artisan about"

      - name: âŒ Teardown
        run: make down

  symfony-test:
    name: ğŸ“Š Test Symfony
    runs-on: ubuntu-latest

    steps:
      - name: ğŸ’¾ Checkout code
        uses: actions/checkout@v4

      - name: ğŸ“‚ Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: ğŸ›  Prepare .env and extract PHP_VERSION
        run: |
          cp .env.example .env
          echo "PHP_VERSION=$(grep PHP_VERSION .env | cut -d '=' -f2)" >> $GITHUB_ENV

      - name: ğŸ’¾ Restore build cache
        uses: actions/cache@v4
        with:
          path: /tmp/.buildx-cache-${{ env.PHP_VERSION }}
          key: ${{ format('{0}-php-{1}-{2}', runner.os, env.PHP_VERSION, hashFiles(format('docker/php/{0}/Dockerfile', env.PHP_VERSION)) ) }}
          restore-keys: |
            ${{ runner.os }}-php-${{ env.PHP_VERSION }}-

      - name: ğŸ’ª Build Docker environment (with cache)
        run: |
          docker buildx create --use
          docker buildx build \
          --tag php-dev:${{ env.PHP_VERSION }} \
          --file docker/php/${{ env.PHP_VERSION }}/Dockerfile \
          --cache-from=type=local,src=/tmp/.buildx-cache-${{ env.PHP_VERSION }} \
          --cache-to=type=local,dest=/tmp/.buildx-cache-new-${{ env.PHP_VERSION }} \
          --load \
          .

      - name: ğŸ’¾ Save updated cache
        if: always()
        run: |
          rm -rf /tmp/.buildx-cache-${{ env.PHP_VERSION }}
          mv /tmp/.buildx-cache-new-${{ env.PHP_VERSION }} /tmp/.buildx-cache-${{ env.PHP_VERSION }}

      - name: ğŸš€ Start Symfony stack
        run: make up-pgsql

      - name: ğŸ¤– Create new Symfony App
        run: make composer-create-project project=symfony/skeleton name=symfony-test

      - name: ğŸ”§ Run Symfony console about
        run: make run-php-command project=symfony-test command="bin/console about"

      - name: âŒ Teardown
        run: make down